[platformio]
default_envs = esp32-s3-devkitc-1
src_dir = .

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
  https://github.com/pschatzmann/arduino-audio-tools.git
build_flags =
  -DCORE_DEBUG_LEVEL=1

; Quand tu recevras ton ESP32-S3 demain, tu pourras essayer cet environnement.
; Vérifie simplement que les pins I2S correspondent bien à ta nouvelle carte.
[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
lib_deps =
  https://github.com/pschatzmann/arduino-audio-tools.git
build_flags =
  -DCORE_DEBUG_LEVEL=1
